# Generated by Django 5.1.6 on 2025-03-01 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmGenerator', '0002_seasonplayerstats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seasonplayerstats',
            old_name='appearences',
            new_name='appearances',
        ),
    ]
