# Generated by Django 5.1.6 on 2025-03-01 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmGenerator', '0003_rename_appearences_seasonplayerstats_appearances'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonplayerstats',
            name='player_name',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
    ]
