# Generated by Django 3.2.16 on 2025-03-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmGenerator', '0004_seasonplayerstats_player_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonplayerstats',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='seasonplayerstats',
            name='appearances',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='seasonplayerstats',
            name='assists',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='seasonplayerstats',
            name='clean_sheets',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='seasonplayerstats',
            name='goals',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='seasonplayerstats',
            name='player_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='seasonplayerstats',
            name='season',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='seasonplayerstats',
            unique_together={('story', 'season', 'player_name')},
        ),
        migrations.RemoveField(
            model_name='seasonplayerstats',
            name='season_avg',
        ),
    ]
