# Generated by Django 3.2.16 on 2025-03-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmGenerator', '0005_auto_20250302_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasonplayerstats',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
