# Generated by Django 3.2.16 on 2025-03-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmGenerator', '0006_alter_seasonplayerstats_average_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonplayerstats',
            name='red_cards',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seasonplayerstats',
            name='yellow_cards',
            field=models.IntegerField(default=0),
        ),
    ]
