# Generated by Django 3.2.16 on 2025-03-02 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmGenerator', '0007_auto_20250302_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='cmGenerator.story')),
            ],
            options={
                'ordering': ['season'],
                'unique_together': {('story', 'season')},
            },
        ),
    ]
