# Generated by Django 3.2.16 on 2025-03-02 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmGenerator', '0009_seasonawards'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonawards',
            name='champions_league_winner',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='seasonawards',
            name='conference_league_winner',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='seasonawards',
            name='europa_league_winner',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='seasonawards',
            name='super_cup_winner',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
