# Generated by Django 3.2.25 on 2025-03-03 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmGenerator', '0011_seasonplayerstats_overall_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=10)),
                ('player_name', models.CharField(max_length=100)),
                ('club', models.CharField(max_length=100)),
                ('fee', models.CharField(max_length=50)),
                ('direction', models.CharField(choices=[('in', 'In'), ('out', 'Out')], max_length=5)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='cmGenerator.story')),
            ],
            options={
                'unique_together': {('story', 'season', 'player_name', 'direction')},
            },
        ),
    ]
